/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_unisb_cs_depend_ccs_sem_exporters_bcg_BCGWriter */

#ifndef _Included_de_unisb_cs_depend_ccs_sem_exporters_bcg_BCGWriter
#define _Included_de_unisb_cs_depend_ccs_sem_exporters_bcg_BCGWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_unisb_cs_depend_ccs_sem_exporters_bcg_BCGWriter
 * Method:    open0
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_de_unisb_cs_depend_ccs_1sem_exporters_bcg_BCGWriter_open0
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     de_unisb_cs_depend_ccs_sem_exporters_bcg_BCGWriter
 * Method:    writeTransition0
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_unisb_cs_depend_ccs_1sem_exporters_bcg_BCGWriter_writeTransition0
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     de_unisb_cs_depend_ccs_sem_exporters_bcg_BCGWriter
 * Method:    close0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_unisb_cs_depend_ccs_1sem_exporters_bcg_BCGWriter_close0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
